### PR TITLE
Launch website based on ARL policy

### PR DESCRIPTION
**Pull request by fulldecent**

### CODE REVIEW

**Comment by fulldecent** [comment]
This is a starting point for #85

**Comment by tomberek** [comment]
Let's break out the root LICENSE.md as a separate issue.

**Comment by fulldecent** [comment]
Thank you for the review and support!

**Comment by tomberek** [comment]
It's been a busy month. Looking back into this now. We're starting with a blank slate at the code.mil.page repo. I'll start moving some of this over.

**Comment by fulldecent** [comment]
Sounds good, let me know if/how I can help.

**Comment by fulldecent** [comment]
Please let me know if there is an interest in publishing this repository to CODE.mil. I can update this PR as necessary to accomplish that.

**Comment by jordangov** [comment]
Sorry for the delay here. We've had people rolling off of DDS and shifting teams. I'll be looking into this effort more int he coming weeks.

**Comment by fulldecent** [comment]
Excellent, thanks for the heads up. I'm still around here.

**Comment by fulldecent** [comment]
Hello @jordangov, @tomberek, please let me know if there is a different person I may address this to.

This PR is a minimal viable product for code.mil. This is ready to release early and release often, so I want to give you something that is shippable. Then we can iterate from there as I am sure the great discussions here will continue to pan out.

**Comment by jordangov** [comment]
@fulldecent Thank you! We get it, and we want that... but resources are stretched thin. I'm hoping to have time late next week to jump back in. It is *not* falling off my plate.

**Comment by jordangov** [comment]
Hi! So I'm generally in favor of this PR, but there are some things I'd like to do before publishing it, and because you're PR'ing into thew `gh-pages` branch I can't merge it without publishing. :)

Let's switch the branch you're merging into to this new one: `static-site` and then we can iterate on the development. Thanks!

**Comment by jordangov** [comment]
Nevermind! I was able to change it. I'll be working on a number of changes before we can merge into `gh-pages` for publication:

- [ ] uswds integration
- [ ] integration of FAQs
- [ ] some jekyll tweaks
- [ ] integration of google form (?)
- [ ] content tweaks (breaking up the implementation page a bit, updating, etc)

**Comment by fulldecent** [comment]
Very cool. Thank you! I'll open a new PR now to merge static-site to gh-pages. This will represent the minimally viable product for launch.

**Comment by jordangov** [comment]
Please make your PRs merge into the `static-site` branch, not gh-pages. We'll have a few different updates for this that may come in from various sources (you, me, others?). I'll make a PR into `gh-pages` once it's ready which can then get reviewed by other DDS folks.

**Comment by fulldecent** [comment]
Oops. Just made https://github.com/deptofdefense/code.mil/pull/126 for the launch party.

And yes. All changes will come into this new static-site branch while we're working on it.

**Comment by fulldecent** [comment]
Here are some bite-sized commits addressing https://github.com/deptofdefense/code.mil/pull/92#issuecomment-337670592

**Comment by missyk5150** [comment]
"Launch is a beautiful thing, but it's not such a big deal. Once you are launched, it will attract more contributors that get you to where you really want to be"
      ~fulldecent 2017~

I just thought this was very well said... so i put it in "quotations" and dated it is all.  

Every time i learn a little more about coding or feel the information i have obtained since would be enough to suffice....... the less i seem to know for helping this project.. Yet as small as i may feel,  I was here from the day it opened and i still have no idea where to start with any of this.. LOL. I 'll figure it out someday. Always looking up to you and much respect for the work you do.
~MK

**Comment by jordangov** [comment]
Thank you for your comment! You are absolutely right about that quote. And as for where you can help: there are all sorts of opportunities, both technical and not. Comments on our process or guidance, language crafting, design (we still need a logo) and content architecture, and of course the code for the site itself.

Once we have an initial site launched it will be much easier to track enhancements. I'm hoping that will happen sooner rather than later.

**Pull request merged**
