### PR TITLE
Update LICENSE-agreement.md

### PR DESCRIPTION
**Pull request by tomberek**
`The DoD` seems to imply this is policy. `This Work` may be more appropriate.

### CODE REVIEW

**Comment by BrandonBouier** [comment]
@tomberek looks good, but I'd like @shawoods to review before merging

**Comment by nickrobson** [comment]
Does this sentence not imply that you need a Signed-off-by line in your commit; which is lacking in this PR?

**Comment by BrandonBouier** [comment]
@nickrobson as stated at the top of https://github.com/deptofdefense/code.mil/blob/master/CONTRIBUTING.md, you don't need to have a Signed-off-by line in your PR for the license agreement:

"Note: CONTRIBUTING.md is for software projects. You do not need to follow the DCO process for commenting on the Code.mil repository documentation, like CONTRIBUTING.md or LICENSE-agreement.md."

**Comment by nickrobson** [comment]
Alright - my bad.

**Pull request closed without merging**
