### PR TITLE
Delete empty file

### PR DESCRIPTION
**Pull request by fulldecent**

### CODE REVIEW

**Comment by tomberek** [comment]
There is a link at [defense.gov] pointing to that file. There might be more elsewhere. Yes, that was probably a mistake and this is a hack to keep that link from breaking. Let's keep this for a few more days, then we'll merge. Thanks!

[defense.gov]: https://www.defense.gov/News/News-Releases/News-Release-View/Article/1092364/dod-announces-the-launch-of-codemil-an-experiment-in-open-source

**Comment by fulldecent** [comment]
I have contacted the DoD webmaster to request that link be updated to this repo's main page.

**Comment by shawoods** [comment]
Just got word the defense.gov press release should be updated shortly. Once that happens, we can delete the file.

**Comment by tomberek** [comment]
Complete, thanks @fulldecent

**Pull request merged**
