### PR TITLE
Clarifies future alterations to the agreement and DoD expression of c…

### PR DESCRIPTION
**Pull request by Schwad**
Clarifies future alterations to the agreement and DoD expression of copyright protections. Signed-off-by: Nicholas Schwaderer <nicholas.schwaderer@gmail.com>

### CODE REVIEW

**Comment by shawoods** [comment]
@Schwad Thanks for the suggestion! We will take this under consideration. Making commitments about the copyright status in foreign countries gets tricky, so we'll have to think through that some more. Any thoughts on that?

**Comment by Schwad** [comment]
@shawoods Thank you for your kind words. I purposely phrased the additional language about copyright status to not be a binding anchor on DoD but rather a statement of good faith. 

This will be a signal to developers that the language `In places where DoD has no copyright protections in this Work,` won't be used as a 'gotcha' against contributors.

**Comment by Schwad** [comment]
In the similar vein (positive signalling), I think that subsection `d.` will help show that there is no intent to undergo retroactive revisions in future.

**Comment by BrandonBouier** [comment]
@Schwad, while we're not going to merge this specific pull request, we are intending to update the agreement, and take what you are suggesting here into account.

**Comment by Schwad** [comment]
If I have read recent commits correctly:

```
Based on the feedback, we updated our strategy to move away from contract law and instead focus on the contribution process. We deleted the LICENSE-agreement.md file. Our updated strategy is fully captured in [CONTRIBUTING.md](/Proposal/CONTRIBUTING.md). We think the updated strategy avoids the complications of using contract law and also the perception that we're creating new licenses. We hope this will keep our practices more consistent with the open source and free software communities. We intend to use widely adopted licenses for our projects.
```

It would appear that you are doing away with the file altogether and making a good faith effort to move towards commonly used licensing such as the `MIT` license (although it may be something else). I can heartily say that that is a significant improvement even on my changes and I am pleased to see you heading in this direction.

**Comment by BrandonBouier** [comment]
@Schwad yes we are looking to do away with the LICENSE-agreement.md file, based on feedback from you & others (I, for one, appreciate that you actually took the time to submit a pull request).

Thank you very much.

**Comment by Schwad** [comment]
@BrandonBouier I'm very glad to hear it. As a software engineer who is passionate about the work you do, I figure actually taking a crack at a pull request is more helpful than a comment. Best of luck going forward and I'll keep a close eye on your work. Thanks!

**Pull request closed without merging**
