### PR TITLE
Implement CC0, fixes #37

### LINKED ISSUE #37: Consider using CC0 for this project
The goal of this license as it stands is:

* Allow the US Military to publish things
* Confirm that US copyright does not apply
* Denounce any foreign copyright if it exists
* Require positive identification of new contributions

There is already an existing license that achieves this, has been thoroughly reviewed, and enjoys widespread adoption. Namely, the [CC0 license](https://creativecommons.org/publicdomain/zero/1.0/legalcode).

**Additionally, the CC0 makes many disclaimers about the published material so as to limit liabilities that the publisher assumes by making publication. Specifically, this addresses issue #36.**

Note: CC0 does NOT satisfy the current requirement of DOSA 1.0draft in using a Developer’s Certificate of Origin. No problem. Instead, this requirement should be discussed in CONTRIBUTORS.md.

### PR DESCRIPTION
**Pull request by fulldecent**
This project CAN NOT use GPL, BSD, MIT and other licenses because those licenses require that you have ownership of the code, which you do not!

CC0 disclaims any ownership of code and is likely the only appropriate license for your situation.

### CODE REVIEW

**Comment by tomberek** [comment]
This project's purpose is precisely to discover if there is a means or mechanism to use those licenses. Just to be clear, we are not proposing this effort as DoD-wide policy, simply as another possibility. And it is still DRAFT, so keep the suggestions coming!

Our hesitation to simply use CC0 is best expressed by their own FAQ:
https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software

Because our express desire to explore the re-use of other licenses, I am closing this PR unmerged. Feel free to reopen to discuss/respond.

**Comment by konklone** [comment]
@tomberek I know you know this, but for the benefit of other readers, the [CC FAQ answer about software](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software) you linked to says something different about CC0:

> Also, the CC0 Public Domain Dedication is GPL-compatible and acceptable for software. For details, [see the relevant CC0 FAQ entry](https://wiki.creativecommons.org/wiki/CC0_FAQ#May_I_apply_CC0_to_computer_software.3F_If_so.2C_is_there_a_recommended_implementation.3F).

That link to the CC0 FAQ entry says:

> Yes, CC0 is suitable for dedicating your copyright and related rights in computer software to the public domain, to the fullest extent possible under law. Unlike CC licenses, which should not be used for software, CC0 is compatible with many software licenses, including the GPL.

It also mentions that the OSI has not approved it, due to patent concerns:

> However, CC0 has not been approved by the Open Source Initiative and does not license or otherwise affect any patent rights you may have. You may want to consider using an approved OSI license that does so instead of CC0, such as GPL 3.0 or Apache 2.0.

Because of this, [Creative Commons commented on the White House proposed source code policy](https://github.com/WhiteHouse/source-code-policy/issues/149), saying:

> Thus, Creative Commons recommends that these government works should be released under the [CC0 Public Domain Dedication](https://creativecommons.org/publicdomain/zero/1.0/legalcode), which waives any copyright that might apply, accompanied by a standard non-assertion pledge (nonassert) that indicates that the U.S. government will not to seek to enforce patent rights it may have against reusers of the software.

18F is considering adopting such a non-assertion pledge to clear up any issues over patents for avoidance of doubt. That said, in our almost 3 years using CC0, we've never had any issues come up relating to patents, which is why we haven't done anything about it to date.

But that's all to say that the only issue that OSI or CC have ever raised about applying CC0 to software is around patents, and there are clear ways to remove patents as a concern.

**Comment by johnmod3** [comment]
There was a hack we looked at a while back that could work: if DoD designated NASA as an agent for releasing government employee created works then NASA could release it under any open source license since NASA can create copyright

**Comment by jbjonesjr** [comment]
To add to the reading material, here is a discussion related to using the cc0 for software: https://github.com/github/choosealicense.com/issues/33

**Background:** GitHub manages an Open Source project (yes, we do Open Source too) that attempts to make it easier for developers to choose the proper Open Source License for their efforts (choosealicense.com). GitHub has decided not to include the cc0 in this list of suggested licenses, and the issue linked above is one of the discussions about it.

---

Personal opinion of @jbjonesjr, not my employer, friends, or dog: Licenses are hard. Software is hard. Naming may still be harder (as demonstrated by this repo :) ). However, providing a legal framework to empower the choice of a proper license (whether it be BSD, GLP, cc0, or WTFLP) should help the situation.

**Comment by konklone** [comment]
> To add to the reading material, here is a discussion related to using the cc0 for software:
> github/choosealicense.com#33
> ...
> GitHub has decided not to include the cc0 in this list of suggested licenses, and the issue linked above is one of the discussions about it.

@jbjonesjr That discussion thread doesn't discuss CC0. The thread was about including CC licenses more generally. At the time the thread was opened, choosealicense.com did include CC0, but was replaced [in this thread with Unlicense](https://github.com/github/choosealicense.com/pull/38) for the reason that Unlicense seemed simpler.

There is still a CC0 page on choosealicense.com: https://choosealicense.com/licenses/cc0-1.0/

**Comment by fulldecent** [comment]
A big distinction between GitHub recommendation and DoD use case is that GitHubs audience is people that have copyright to their own work. DoD  does not have time to write off it's on works. Therefore githubs premise for excluding CC0 does not apply here.

**Comment by jbjonesjr** [comment]
@konklone You're right, good catch. I was navigating through multiple issues, and , and thought that was the root for some of the cc0 statements, but was not. I'm going to strikethrough my comment above to clarify.

That said, as @konklone mentions above, CAL "recommends" Unlicense for public domain software works, but the site does have details on cc0, and is linked to from under the `Non-Software Licenses` section.

@fulldecent 
> Therefore githubs premise for excluding CC0 does not apply here.

Of course. Just trying to provide more details and prior work and discussion on the licenses in question.

**Pull request closed without merging**
