### PR TITLE
[ON HOLD (outdated master)] Eliminate “smart quotes” (and use consistent quote style)

### PR DESCRIPTION
**Pull request by rthbound**
Previously the repository contained a mixture of straight and curly quotes. This edit changes curly quotation marks or apostrophes to straight ones.

### CODE REVIEW

**Comment by jordangov** [comment]
Awesome, thank you! We'll need to wait for the merge into `master`, hopefully very soon.

**Comment by jordangov** [comment]
Oh wait... I just noticed that this is changing what's in `master` currently. Please note the *massive* PR #126 coming in hot. This PR will most likely not survive that. :/

But we still appreciate it! And will appreciate content review like this on that new content.

**Comment by rthbound** [comment]
I'm happy to rebase and rescan once that goes in, @jordangov

**Comment by jordangov** [comment]
Ok, the files will be completely different (the files you've changed don't exist any more), so I'm going to close this PR, but please do rescan after the merge!

**Pull request closed without merging**
